### ISSUE TITLE
"/" not accepted in searchRepos 's query

### ISSUE THREAD

**Issue by dev590t** [47degrees/github4s#634] opened 2021-04-04 14:55 UTC
## Description
I can't find the repository `sterglee/scalalab` with searchRepos
## Reproduce bug
```
val searchRepos = gh.repos.searchRepos("sterglee/scalalab", Nil)
val response = searchRepos.unsafeRunSync()
response.result match {
  case Left(e) => println(s"Something went wrong: ${e.getMessage}")
  case Right(r) => println(r)
}
```
That print:
```
SearchReposResult(0,false,List())
```
### Expected
But the repository exist. And I can find it with REST API
```
curl   -H "Accept: application/vnd.github.v3+json"   https://api.github.com/search/repositories?q=sterglee%2Fscalalab
```
I have also directly search `sterglee/scalalab` in github. github can find the repository.

`searchRepos` shouldn't return a empty list.

**Comment by BenFradet** [comment] 2021-04-06 09:44
hey, did you solve the issue in the end?

**Comment by zhenleibb** [comment] 2021-04-07 14:06
I have tested with `gh.repos.searchRepos("47degrees/github4s", Nil)`, it doesn't work also. 

 [The specification](https://github.com/47degrees/github4s/blob/136848e16cbccaef0b6cde45a7254e7f0bc0be7b/github4s/src/main/scala/github4s/interpreters/RepositoriesInterpreter.scala#L68) of `searchRepos` don't precise if `/` is accepted in its argument `query`. I'm not sure that is a bug, or is a expected behavior. So I have close the issue, and replace `gh.repos.searchRepos("sterglee/scalalab", Nil)` by `gh.repos.searchRepos("scalalab", Nil)` in my code.

But I feel it is a bug,  `params = Map("q" -> s"${encode(query, "utf-8")}+${searchParams.map(_.value).mkString("+")}"),` this line in the implementation should accept `/` in `query`.

I reopen the issue.

**Comment by BenFradet** [comment] 2021-04-08 09:20
`curl https://api.github.com/search/repositories?q=sterglee%2Fscalalab` does work so I agree there is an issue with the lib

**Comment by josiah14** [comment] 2021-07-30 16:04
I believe I've identified root cause. [RepositoryInterpreter.scala#L77](https://github.com/47degrees/github4s/blob/main/github4s/src/main/scala/github4s/interpreters/RepositoriesInterpreter.scala#L77) encodes the query parameters using a `java.net.URLEncoder`, which converts any `/`s into a `%2F`, which is no problem so far.  The issue crops up when a second encoding happens at [Http4sSyntax.scala#L62](https://github.com/47degrees/github4s/blob/main/github4s/src/main/scala/github4s/http/Http4sSyntax.scala#L62) where a second encoding happens via an `org.http4s.Uri` encoder, which then transforms the `%` in the `%2F` into a `%25`, transforming the entire section into `%252F`. The Github API does not know how to unravel multiple layers of encoding like this, and so it most likely treats the latter 2F as literal and part of the search pattern, which results in a successful search but with zero results.

**Comment by josiah14** [comment] 2021-07-30 19:55
`java.net.URLEncoder` appears to be redundant since every URL passed to the HttpClient gets encoded by `Http4sSyntax.RequestBuilderOps.toUri` anyway.

I think the best way to resolve this, therefore, is by stripping out the usages of `java.net.URLEncoder` and adding some tests to guard against a bug like this getting reintroduced in the future.

**Comment by dev590t** [comment] 2021-07-31 18:24
> I think the best way to resolve this, therefore, is by stripping out the usages of java.net.URLEncoder and adding some tests to guard against a bug like this getting reintroduced in the future.

Is it possible to use the type system of Scala to guard against a bug like this?
For instance
```
case class NotEncodedQuery(value : String)
val queryString : NotEncodedQuery = ???
val verbatimQuery = URI(Query.unsafeFromString(Uri.encode(queryString.value)))
```

**Comment by josiah14** [comment] 2021-08-02 16:09
@dev590t That's an interesting an worthwhile thought. I'm not sure there's a way to ensure the query string is not encoded though without incurring extra runtime overhead since the query string itself is provided by the library consumer. It would make sense to me to ensure we aren't multi-encoding the string within the library itself, but to assume that just because we haven't encoded it yet that the end user hasn't provided an already encoded string may be a bit presumptuous and thus difficult to really wrap into the type system in a way that seems to indicate we know for sure whether something we've received is encoded or not.

@Daenyth Do you have any input on this? I'm hoping I'm wrong and there's a reasonable way to wrap this sort of validation into the type-system without overhead (or with little-enough overhead that it's justified).

**Comment by Daenyth** [comment] 2021-08-03 12:35
I don't think it's worth making the types more complex to fix this; we can just have a unit test in this case

**Closed** 2021-08-12 12:12 UTC
