### ISSUE TITLE
Traversing with Pagination

### ISSUE THREAD

**Issue by elbaulp** [47degrees/github4s#285] opened 2019-10-26 20:55 UTC
Is there a way of traversing with Pagination as explained [here](https://developer.github.com/v3/guides/traversing-with-pagination/#consuming-the-information)? I could not find anything in the docs or code

So far, the only way I could find to do it is to look at the `link` header in the response headers. But seems a very complicated way to do it, since all tags are shown as a single string:

```
Link | <https://api.github.com/organizations/9919/members?page=1&per_page=1>;  rel="prev",  <https://api.github.com/organizations/9919/members?page=3&per_page=1>;  rel="next",  <https://api.github.com/organizations/9919/members?page=214&per_page=1>;  rel="last",  <https://api.github.com/organizations/9919/members?page=1&per_page=1>;  rel="first"
```

**Comment by BenFradet** [comment] 2019-10-28 07:33
Hey, here is how I did it: https://github.com/BenFradet/dashing/blob/e452e9c1d7032ec8199ed9de370680be945a16ee/server/src/main/scala/dashing/server/utils.scala#L112-L135

**Comment by dcsobral** [comment] 2020-03-25 21:31
@BenFradet Your solution has two issues. First, by enumerating the pages beforehand, it may fail due to changes in number of pages. Open PRs filter might find itself fetching a page that does not exist, and there's always the risk of fetching too few pages.

The second is that github API documentation repeatedly emphasizes that one must not construct the URL, but use the one given. The inability to do that is a flaw on github4s API.

**Comment by BenFradet** [comment] 2020-03-29 10:40
closing as dupe of #169

**Closed by BenFradet** 2020-03-29 10:40 UTC
